<div style="text-align: center; font-size: 8pt; color: #9ca3af; padding: 10px 20px; border-top: 1px solid #e5e7eb;">
    Strona <span class="pageNumber"></span> z <span class="totalPages"></span>
    | Generated by VibeTravels | {{ now()->format('d.m.Y') }}
</div>
