<?php

declare(strict_types=1);

namespace App\Events;

use App\Models\AIGeneration;
use App\Models\TravelPlan;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

/**
 * Plan Generated Event
 *
 * Dispatched when a travel plan has been successfully generated by AI.
 * Can be used to trigger notifications, analytics, or other side effects.
 */
class PlanGenerated
{
    use Dispatchable, SerializesModels;

    /**
     * Create a new event instance.
     */
    public function __construct(
        public TravelPlan $travelPlan,
        public AIGeneration $aiGeneration
    ) {}
}
