<?php

/**
 * Migration: Create PDF Exports Table
 *
 * Purpose: Track PDF export events for analytics and user history
 *
 * Tables Affected: pdf_exports
 *
 * Features:
 * - Metadata-only tracking (PDFs generated on-demand, not stored)
 * - Multiple exports per plan allowed (1:N relationship)
 * - File size tracking for infrastructure planning
 * - Export timestamp for usage analytics
 *
 * Analytics Usage:
 * - Export rate: % of plans exported at least once
 * - Average exports per plan
 * - Popular export times (for infrastructure scaling)
 *
 * PDF Generation:
 * - Server-side rendering via Spatie Laravel PDF (Chromium)
 * - Generated on-demand (no caching in MVP)
 * - Watermark: "Generated by VibeTravels"
 *
 * Security Notes:
 * - Foreign key CASCADE delete when plan or user deleted
 * - No file storage (only metadata)
 *
 * Related Tables: travel_plans (N:1), users (N:1)
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('pdf_exports', function (Blueprint $table) {
            // Primary key
            $table->id();

            // Foreign keys
            $table->unsignedBigInteger('travel_plan_id')->comment('Travel plan being exported');
            $table->unsignedBigInteger('user_id')->comment('User who requested export');

            // Export metadata
            $table->integer('file_size_bytes')->nullable()->comment('Generated PDF file size in bytes (for infrastructure planning)');

            // Export timestamp
            // Note: Using exported_at instead of created_at for semantic clarity
            $table->timestamp('exported_at')->useCurrent()->comment('When PDF was generated and downloaded');

            // Foreign key constraints
            // ON DELETE CASCADE: when plan deleted, export history deleted
            $table->foreign('travel_plan_id', 'fk_pdf_exports_travel_plan_id')
                ->references('id')
                ->on('travel_plans')
                ->onDelete('cascade')
                ->onUpdate('restrict');

            // ON DELETE CASCADE: when user deleted, export history deleted (GDPR)
            $table->foreign('user_id', 'fk_pdf_exports_user_id')
                ->references('id')
                ->on('users')
                ->onDelete('cascade')
                ->onUpdate('restrict');

            // Indexes for analytics queries
            $table->index('travel_plan_id', 'idx_pdf_exports_plan'); // Exports per plan
            $table->index('user_id', 'idx_pdf_exports_user'); // Exports per user
        });

        // Add table comment
        DB::statement("ALTER TABLE pdf_exports COMMENT 'PDF export event tracking (metadata only, 1:N with travel_plans)'");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('pdf_exports');
    }
};
